### PR TITLE
Porting to Devart

### PR DESCRIPTION
**Pull request by jeffreywilbur**
We needed a Devart implementation for those using their driver rather than the official Oracle managed access driver (particularly in Net Core projects). This port facilitates that.

### CODE REVIEW

**Comment by mookid8000** [comment]
cool 👍 could you click the CLA link above and sign it?

**Comment by jeffreywilbur** [comment]
@mookid8000 Yeah, I have, it apparently is not reflected on the PR for some reason though.

**Comment by mookid8000** [comment]
it's out as 1.0.0-a3 in a few minutes 👍

**Comment by jeffreywilbur** [comment]
Hey, thanks for the merge!
could you add a nuget package for that? I saw you updated to 1.0.0-a3, but
that only includes the normal Rebus.oracle it seems and not
Rebus.oracle.devart

**Comment by mookid8000** [comment]
Hi there, are you not receiving my email?

Please get back to me ASAP if you are not receiving my emails – I have sent a couple already 🙂

**Pull request merged**
